AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - lib/one_gadget/builds/*.rb

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/IndentHeredoc:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: true
  Max: 120

Metrics/MethodLength:
  Enabled: false

Naming/FileName:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false

Rails:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/TrailingBodyOnMethodDefinition:
  Enabled: false
