name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  actions: write
  contents: read
  id-token: write

jobs:
  test:

    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.ruby-version == 'head' }}
    strategy:
      matrix:
        ruby-version: ['3.1', '3.2', '3.3', '3.4', 'head']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Install apt packages
      run: sudo apt update && sudo apt install -yy grep binutils-multiarch
    - name: Run tests
      run: bundle exec rake
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
    - name: Publish code coverage
      if: ${{ success() && env.CC_TEST_REPORTER_ID }}
      uses: qltysh/qlty-action/coverage@v1
      with:
        oidc: true
        files: coverage/coverage.json
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
